apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    deployment: persistentVolume.log
  name: persistent-volume-log
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  storageClassName: standard
  hostPath:
    path: /c/
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain