apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    depployment: persistentVolumeClaim.log
  name: persistent-volume-claim-log
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: persistent-volume-log