apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    depployment: persistentVolumeClaim.secrets
  name: persistent-volume-claim-secrets
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: persistent-volume-secrets