apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    depployment: persistentVolumeClaim.data
  name: persistent-volume-claim-data
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: persistent-volume-data