apiVersion: v1
kind: Service
metadata:
  annotations:
    deployment: app-lanchonete
  name: service-app
  namespace: default
spec:
  ports:
  - name: app
    port: 1443
    targetPort: 443
    protocol: TCP
  selector:
    app: app
  type: LoadBalancer
  externalIPs:
  - 80.11.12.10
status:
  loadBalancer:
    ingress:
    - ip: 192.0.2.127